/* eslint-disable @typescript-eslint/ban-ts-comment */
import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import { getOptionsForVote } from "../utils/getRandomStand";
import { useEffect, useState } from "react";
import type { FormattedStand } from "./api/jjbaData";
import data from "../pages/api/data/all_data.json";
import jojoLogo from "../../public/jjba_pixel_logo.png";
import { Stand } from "./components/stand-card";

const Home: NextPage = () => {
  const [ids, setIds] = useState([0, 0]);

  useEffect(() => {
    setIds(getOptionsForVote());
  }, []);

  const [first, second] = ids;

  console.log(...ids);

  // @ts-ignore
  const firstStand = trpc.data.getStandById.useQuery({ id: first });
  // @ts-ignore
  const secondStand = trpc.data.getStandById.useQuery({ id: second });



  return (
    <>
      <Head>
        <title>OP-T3 | Battle of the Stands</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-auto flex h-screen max-w-screen-sm flex-col justify-center gap-6">
        <header className="justify-right absolute top-0 right-0 flex flex-col p-4">
          <div className="title text-center text-4xl border-2">OP-T3</div>
          <div className="title text-right text-4xl"><a href="'/vote">Vote</a></div>
          <div className="title text-right text-4xl"><a href="'/rankings">Rankings</a></div>
        </header>
        <div className="text-center text-2xl">Which Stand is more OP?</div>
        <div className="flex items-center justify-around p-8">
          {firstStand.isLoading ? (
            <h1>Loading</h1>
          ) : (
            <Stand stand={firstStand.data} />
          )}
          <div className="p-8 italic">or</div>
          {secondStand.isLoading ? (
            <h1>Loading</h1>
          ) : (
            <Stand stand={secondStand.data} />
          )}
        </div>
      </div>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
